(deftheme doom-molokai
  "Created 2020-01-05.")

(custom-theme-set-variables
 'doom-molokai
 '(ansi-color-names-vector ["#1c1e1f" "#e74c3c" "#b6e63e" "#e2c770" "#268bd2" "#fb2874" "#66d9ef" "#d6d6d4"]))

(custom-theme-set-faces
 'doom-molokai
 '(bold ((((class color) (min-colors 257)) (:weight bold :foreground nil)) (((class color) (min-colors 256)) (:weight bold :foreground nil)) (((class color) (min-colors 16)) (:weight bold :foreground nil))))
 '(italic ((t (:slant italic))))
 '(bold-italic ((t (:inherit (bold italic)))))
 '(fringe ((((class color) (min-colors 257)) (:inherit default :foreground "#4e4e4e")) (((class color) (min-colors 256)) (:inherit default :foreground "#454545")) (((class color) (min-colors 16)) (:inherit default :foreground "brightblack"))))
 '(region ((((class color) (min-colors 257)) (:background "#4e4e4e" :foreground nil :distant-foreground "#ababa9" :extend t)) (((class color) (min-colors 256)) (:background "#454545" :foreground nil :distant-foreground "#b2b2b2" :extend t)) (((class color) (min-colors 16)) (:background "brightblack" :foreground nil :distant-foreground "brightwhite" :extend t))))
 '(highlight ((((class color) (min-colors 257)) (:background "#fd971f" :foreground "#1B2229" :distant-foreground "#ffffff")) (((class color) (min-colors 256)) (:background "#fd971f" :foreground "black" :distant-foreground "#ffffff")) (((class color) (min-colors 16)) (:background "brightred" :foreground "black" :distant-foreground "brightwhite"))))
 '(cursor ((((class color) (min-colors 257)) (:background "#fb2874")) (((class color) (min-colors 256)) (:background "#fb2874")) (((class color) (min-colors 16)) (:background "magenta"))))
 '(shadow ((((class color) (min-colors 257)) (:foreground "#555556")) (((class color) (min-colors 256)) (:foreground "#6b6b6b")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(minibuffer-prompt ((((class color) (min-colors 257)) (:foreground "#fd971f")) (((class color) (min-colors 256)) (:foreground "#fd971f")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(tooltip ((((class color) (min-colors 257)) (:background "#2d2e2e" :foreground "#d6d6d4")) (((class color) (min-colors 256)) (:background "#252525" :foreground "#dfdfdf")) (((class color) (min-colors 16)) (:background "brightblack" :foreground "brightwhite"))))
 '(secondary-selection ((((class color) (min-colors 257)) (:background "#525254" :extend t)) (((class color) (min-colors 256)) (:background "#515154" :extend t)) (((class color) (min-colors 16)) (:background "brightblack" :extend t))))
 '(lazy-highlight ((((class color) (min-colors 257)) (:background "#9c91e4" :foreground "#1B2229" :distant-foreground "#1B2229" :bold t)) (((class color) (min-colors 256)) (:background "#9c91e4" :foreground "black" :distant-foreground "black" :bold t)) (((class color) (min-colors 16)) (:background "brightmagenta" :foreground "black" :distant-foreground "black" :bold t))))
 '(match ((((class color) (min-colors 257)) (:foreground "#b6e63e" :background "#1B2229" :weight bold)) (((class color) (min-colors 256)) (:foreground "#b6e63e" :background "black" :weight bold)) (((class color) (min-colors 16)) (:foreground "green" :background "black" :weight bold))))
 '(trailing-whitespace ((((class color) (min-colors 257)) (:background "#e74c3c")) (((class color) (min-colors 256)) (:background "#e74c3c")) (((class color) (min-colors 16)) (:background "red"))))
 '(nobreak-space ((t (:inherit default :underline nil))))
 '(vertical-border ((((class color) (min-colors 257)) (:background "#323435" :foreground "#323435")) (((class color) (min-colors 256)) (:background nil :foreground nil)) (((class color) (min-colors 16)) (:background nil :foreground nil))))
 '(link ((((class color) (min-colors 257)) (:foreground "#fd971f" :underline t :weight bold)) (((class color) (min-colors 256)) (:foreground "#fd971f" :underline t :weight bold)) (((class color) (min-colors 16)) (:foreground "brightred" :underline t :weight bold))))
 '(error ((((class color) (min-colors 257)) (:foreground "#e74c3c")) (((class color) (min-colors 256)) (:foreground "#e74c3c")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(warning ((((class color) (min-colors 257)) (:foreground "#e2c770")) (((class color) (min-colors 256)) (:foreground "#e2c770")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(success ((((class color) (min-colors 257)) (:foreground "#b6e63e")) (((class color) (min-colors 256)) (:foreground "#b6e63e")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(font-lock-builtin-face ((((class color) (min-colors 257)) (:foreground "#fd971f")) (((class color) (min-colors 256)) (:foreground "#fd971f")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(font-lock-comment-face ((((class color) (min-colors 257)) (:foreground "#555556")) (((class color) (min-colors 256)) (:foreground "#6b6b6b")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-doc-face ((((class color) (min-colors 257)) (:inherit font-lock-comment-face :foreground "#7f7f80")) (((class color) (min-colors 256)) (:inherit font-lock-comment-face :foreground "#909090")) (((class color) (min-colors 16)) (:inherit font-lock-comment-face :foreground "brightblack"))))
 '(font-lock-constant-face ((((class color) (min-colors 257)) (:foreground "#fd971f")) (((class color) (min-colors 256)) (:foreground "#fd971f")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(font-lock-function-name-face ((((class color) (min-colors 257)) (:foreground "#b6e63e")) (((class color) (min-colors 256)) (:foreground "#b6e63e")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(font-lock-keyword-face ((((class color) (min-colors 257)) (:foreground "#fb2874")) (((class color) (min-colors 256)) (:foreground "#fb2874")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(font-lock-string-face ((((class color) (min-colors 257)) (:foreground "#e2c770")) (((class color) (min-colors 256)) (:foreground "#e2c770")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(font-lock-type-face ((((class color) (min-colors 257)) (:foreground "#66d9ef")) (((class color) (min-colors 256)) (:foreground "#66d9ef")) (((class color) (min-colors 16)) (:foreground "brightcyan"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 257)) (:foreground "#fd971f")) (((class color) (min-colors 256)) (:foreground "#fd971f")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(font-lock-warning-face ((t (:inherit warning))))
 '(font-lock-negation-char-face ((((class color) (min-colors 257)) (:inherit bold :foreground "#9c91e4")) (((class color) (min-colors 256)) (:inherit bold :foreground "#9c91e4")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightmagenta"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 257)) (:inherit bold :foreground "#9c91e4")) (((class color) (min-colors 256)) (:inherit bold :foreground "#9c91e4")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightmagenta"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 257)) (:inherit bold :foreground "#9c91e4")) (((class color) (min-colors 256)) (:inherit bold :foreground "#9c91e4")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightmagenta"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 257)) (:inherit bold :foreground "#9c91e4")) (((class color) (min-colors 256)) (:inherit bold :foreground "#9c91e4")) (((class color) (min-colors 16)) (:inherit bold :foreground "brightmagenta"))))
 '(mode-line ((((class color) (min-colors 257)) (:background "#2d2e2e" :foreground nil :box nil)) (((class color) (min-colors 256)) (:background "#252525" :foreground nil :box nil)) (((class color) (min-colors 16)) (:background "brightblack" :foreground nil :box nil))))
 '(mode-line-inactive ((((class color) (min-colors 257)) (:background "#171819" :foreground "#4e4e4e" :box nil)) (((class color) (min-colors 256)) (:background "#141414" :foreground "#454545" :box nil)) (((class color) (min-colors 16)) (:background "brightblack" :foreground "brightblack" :box nil))))
 '(mode-line-emphasis ((((class color) (min-colors 257)) (:foreground "#fd971f" :distant-foreground "#1c1e1f")) (((class color) (min-colors 256)) (:foreground "#fd971f" :distant-foreground nil)) (((class color) (min-colors 16)) (:foreground "brightred" :distant-foreground nil))))
 '(mode-line-highlight ((((class color) (min-colors 257)) (:inherit highlight :distant-foreground "#1c1e1f")) (((class color) (min-colors 256)) (:inherit highlight :distant-foreground nil)) (((class color) (min-colors 16)) (:inherit highlight :distant-foreground nil))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(header-line ((((class color) (min-colors 257)) (:inherit mode-line :distant-foreground "#1c1e1f")) (((class color) (min-colors 256)) (:inherit mode-line :distant-foreground nil)) (((class color) (min-colors 16)) (:inherit mode-line :distant-foreground nil))))
 '(line-number ((((class color) (min-colors 257)) (:inherit default :foreground "#555556" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil)) (((class color) (min-colors 256)) (:inherit default :foreground "#6b6b6b" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil)) (((class color) (min-colors 16)) (:inherit default :foreground "brightblack" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil))))
 '(line-number-current-line ((((class color) (min-colors 257)) (:inherit (hl-line default) :foreground "#cfc0c5" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil)) (((class color) (min-colors 256)) (:inherit (hl-line default) :foreground "#c1c1c1" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil)) (((class color) (min-colors 16)) (:inherit (hl-line default) :foreground "brightblack" :distant-foreground nil :weight normal :italic nil :underline nil :strike-through nil))))
 '(compilation-column-number ((t (:inherit font-lock-comment-face))))
 '(compilation-line-number ((((class color) (min-colors 257)) (:foreground "#fd971f")) (((class color) (min-colors 256)) (:foreground "#fd971f")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(compilation-error ((t (:inherit error :weight bold))))
 '(compilation-warning ((t (:inherit warning :slant italic))))
 '(compilation-info ((t (:inherit success))))
 '(compilation-mode-line-exit ((t (:inherit compilation-info))))
 '(compilation-mode-line-fail ((t (:inherit compilation-error))))
 '(custom-button ((((class color) (min-colors 257)) (:foreground "#268bd2" :background "#1c1e1f" :box (:line-width 1 :style none))) (((class color) (min-colors 256)) (:foreground "#2686D6" :background nil :box (:line-width 1 :style none))) (((class color) (min-colors 16)) (:foreground "brightblue" :background nil :box (:line-width 1 :style none)))))
 '(custom-button-unraised ((((class color) (min-colors 257)) (:foreground "#9c91e4" :background "#1c1e1f" :box (:line-width 1 :style none))) (((class color) (min-colors 256)) (:foreground "#9c91e4" :background nil :box (:line-width 1 :style none))) (((class color) (min-colors 16)) (:foreground "brightmagenta" :background nil :box (:line-width 1 :style none)))))
 '(custom-button-pressed-unraised ((((class color) (min-colors 257)) (:foreground "#1c1e1f" :background "#9c91e4" :box (:line-width 1 :style none))) (((class color) (min-colors 256)) (:foreground nil :background "#9c91e4" :box (:line-width 1 :style none))) (((class color) (min-colors 16)) (:foreground nil :background "brightmagenta" :box (:line-width 1 :style none)))))
 '(custom-button-pressed ((((class color) (min-colors 257)) (:foreground "#1c1e1f" :background "#268bd2" :box (:line-width 1 :style none))) (((class color) (min-colors 256)) (:foreground nil :background "#2686D6" :box (:line-width 1 :style none))) (((class color) (min-colors 16)) (:foreground nil :background "brightblue" :box (:line-width 1 :style none)))))
 '(custom-button-mouse ((((class color) (min-colors 257)) (:foreground "#1c1e1f" :background "#268bd2" :box (:line-width 1 :style none))) (((class color) (min-colors 256)) (:foreground nil :background "#2686D6" :box (:line-width 1 :style none))) (((class color) (min-colors 16)) (:foreground nil :background "brightblue" :box (:line-width 1 :style none)))))
 '(custom-variable-button ((((class color) (min-colors 257)) (:foreground "#b6e63e" :underline t)) (((class color) (min-colors 256)) (:foreground "#b6e63e" :underline t)) (((class color) (min-colors 16)) (:foreground "green" :underline t))))
 '(custom-saved ((((class color) (min-colors 257)) (:foreground "#b6e63e" :background "#3a4625" :bold t)) (((class color) (min-colors 256)) (:foreground "#b6e63e" :background nil :bold t)) (((class color) (min-colors 16)) (:foreground "green" :background nil :bold t))))
 '(custom-comment ((((class color) (min-colors 257)) (:foreground "#d6d6d4" :background "#4e4e4e")) (((class color) (min-colors 256)) (:foreground "#dfdfdf" :background "#454545")) (((class color) (min-colors 16)) (:foreground "brightwhite" :background "brightblack"))))
 '(custom-comment-tag ((((class color) (min-colors 257)) (:foreground "#525254")) (((class color) (min-colors 256)) (:foreground "#515154")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(custom-modified ((((class color) (min-colors 257)) (:foreground "#268bd2" :background "#1e3342")) (((class color) (min-colors 256)) (:foreground "#2686D6" :background nil)) (((class color) (min-colors 16)) (:foreground "brightblue" :background nil))))
 '(custom-variable-tag ((((class color) (min-colors 257)) (:foreground "#fb2874")) (((class color) (min-colors 256)) (:foreground "#fb2874")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(custom-visibility ((((class color) (min-colors 257)) (:foreground "#268bd2" :underline nil)) (((class color) (min-colors 256)) (:foreground "#2686D6" :underline nil)) (((class color) (min-colors 16)) (:foreground "brightblue" :underline nil))))
 '(custom-group-subtitle ((((class color) (min-colors 257)) (:foreground "#e74c3c")) (((class color) (min-colors 256)) (:foreground "#e74c3c")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(custom-group-tag ((((class color) (min-colors 257)) (:foreground "#9c91e4")) (((class color) (min-colors 256)) (:foreground "#9c91e4")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(custom-group-tag-1 ((((class color) (min-colors 257)) (:foreground "#268bd2")) (((class color) (min-colors 256)) (:foreground "#2686D6")) (((class color) (min-colors 16)) (:foreground "brightblue"))))
 '(custom-set ((((class color) (min-colors 257)) (:foreground "#e2c770" :background "#1c1e1f")) (((class color) (min-colors 256)) (:foreground "#e2c770" :background nil)) (((class color) (min-colors 16)) (:foreground "yellow" :background nil))))
 '(custom-themed ((((class color) (min-colors 257)) (:foreground "#e2c770" :background "#1c1e1f")) (((class color) (min-colors 256)) (:foreground "#e2c770" :background nil)) (((class color) (min-colors 16)) (:foreground "yellow" :background nil))))
 '(custom-invalid ((((class color) (min-colors 257)) (:foreground "#e74c3c" :background "#442724")) (((class color) (min-colors 256)) (:foreground "#e74c3c" :background nil)) (((class color) (min-colors 16)) (:foreground "red" :background nil))))
 '(custom-state ((((class color) (min-colors 257)) (:foreground "#b6e63e" :background "#3a4625")) (((class color) (min-colors 256)) (:foreground "#b6e63e" :background nil)) (((class color) (min-colors 16)) (:foreground "green" :background nil))))
 '(custom-changed ((((class color) (min-colors 257)) (:foreground "#268bd2" :background "#1c1e1f")) (((class color) (min-colors 256)) (:foreground "#2686D6" :background nil)) (((class color) (min-colors 16)) (:foreground "brightblue" :background nil))))
 '(dired-directory ((((class color) (min-colors 257)) (:foreground "#fd971f")) (((class color) (min-colors 256)) (:foreground "#fd971f")) (((class color) (min-colors 16)) (:foreground "brightred"))))
 '(dired-ignored ((((class color) (min-colors 257)) (:foreground "#555556")) (((class color) (min-colors 256)) (:foreground "#6b6b6b")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(dired-flagged ((((class color) (min-colors 257)) (:foreground "#e74c3c")) (((class color) (min-colors 256)) (:foreground "#e74c3c")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(dired-header ((((class color) (min-colors 257)) (:foreground "#268bd2" :weight bold)) (((class color) (min-colors 256)) (:foreground "#2686D6" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold))))
 '(dired-mark ((((class color) (min-colors 257)) (:foreground "#fd971f" :weight bold)) (((class color) (min-colors 256)) (:foreground "#fd971f" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightred" :weight bold))))
 '(dired-marked ((((class color) (min-colors 257)) (:foreground "#fb2874" :weight bold)) (((class color) (min-colors 256)) (:foreground "#fb2874" :weight bold)) (((class color) (min-colors 16)) (:foreground "magenta" :weight bold))))
 '(dired-perm-write ((((class color) (min-colors 257)) (:foreground "#d6d6d4" :underline t)) (((class color) (min-colors 256)) (:foreground "#dfdfdf" :underline t)) (((class color) (min-colors 16)) (:foreground "brightwhite" :underline t))))
 '(dired-symlink ((((class color) (min-colors 257)) (:foreground "#66d9ef" :weight bold)) (((class color) (min-colors 256)) (:foreground "#66d9ef" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightcyan" :weight bold))))
 '(dired-warning ((((class color) (min-colors 257)) (:foreground "#e2c770")) (((class color) (min-colors 256)) (:foreground "#e2c770")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(ediff-fine-diff-A ((((class color) (min-colors 257)) (:background "#5e2038" :weight bold)) (((class color) (min-colors 256)) (:background nil :weight bold)) (((class color) (min-colors 16)) (:background nil :weight bold))))
 '(ediff-fine-diff-B ((t (:inherit ediff-fine-diff-A))))
 '(ediff-fine-diff-C ((t (:inherit ediff-fine-diff-A))))
 '(ediff-current-diff-A ((((class color) (min-colors 257)) (:background "#2d2e2f" :extend t)) (((class color) (min-colors 256)) (:background nil :extend t)) (((class color) (min-colors 16)) (:background nil :extend t))))
 '(ediff-current-diff-B ((t (:inherit ediff-current-diff-A))))
 '(ediff-current-diff-C ((t (:inherit ediff-current-diff-A))))
 '(ediff-even-diff-A ((t (:inherit hl-line))))
 '(ediff-even-diff-B ((t (:inherit ediff-even-diff-A))))
 '(ediff-even-diff-C ((t (:inherit ediff-even-diff-A))))
 '(ediff-odd-diff-A ((t (:inherit ediff-even-diff-A))))
 '(ediff-odd-diff-B ((t (:inherit ediff-odd-diff-A))))
 '(ediff-odd-diff-C ((t (:inherit ediff-odd-diff-A))))
 '(hi-yellow ((((class color) (min-colors 257)) (:background "#e2c770")) (((class color) (min-colors 256)) (:background "#e2c770")) (((class color) (min-colors 16)) (:background "yellow"))))
 '(hi-pink ((((class color) (min-colors 257)) (:background "#fb2874")) (((class color) (min-colors 256)) (:background "#fb2874")) (((class color) (min-colors 16)) (:background "magenta"))))
 '(hi-red-b ((((class color) (min-colors 257)) (:foreground "#e74c3c" :weight bold)) (((class color) (min-colors 256)) (:foreground "#e74c3c" :weight bold)) (((class color) (min-colors 16)) (:foreground "red" :weight bold))))
 '(hi-green ((((class color) (min-colors 257)) (:background "#b6e63e")) (((class color) (min-colors 256)) (:background "#b6e63e")) (((class color) (min-colors 16)) (:background "green"))))
 '(hi-green-b ((((class color) (min-colors 257)) (:foreground "#b6e63e" :weight bold)) (((class color) (min-colors 256)) (:foreground "#b6e63e" :weight bold)) (((class color) (min-colors 16)) (:foreground "green" :weight bold))))
 '(hi-blue ((((class color) (min-colors 257)) (:background "#268bd2")) (((class color) (min-colors 256)) (:background "#2686D6")) (((class color) (min-colors 16)) (:background "brightblue"))))
 '(hi-blue-b ((((class color) (min-colors 257)) (:foreground "#268bd2" :weight bold)) (((class color) (min-colors 256)) (:foreground "#2686D6" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightblue" :weight bold))))
 '(isearch ((((class color) (min-colors 257)) (:foreground "#1B2229" :background "#b6e63e")) (((class color) (min-colors 256)) (:foreground "black" :background "#b6e63e")) (((class color) (min-colors 16)) (:foreground "black" :background "green"))))
 '(isearch-fail ((((class color) (min-colors 257)) (:background "#e74c3c" :foreground "#1B2229" :weight bold)) (((class color) (min-colors 256)) (:background "#e74c3c" :foreground "black" :weight bold)) (((class color) (min-colors 16)) (:background "red" :foreground "black" :weight bold))))
 '(message-header-name ((((class color) (min-colors 257)) (:foreground "#b6e63e")) (((class color) (min-colors 256)) (:foreground "#b6e63e")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(message-header-subject ((((class color) (min-colors 257)) (:foreground "#fd971f" :weight bold)) (((class color) (min-colors 256)) (:foreground "#fd971f" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightred" :weight bold))))
 '(message-header-to ((((class color) (min-colors 257)) (:foreground "#fd971f" :weight bold)) (((class color) (min-colors 256)) (:foreground "#fd971f" :weight bold)) (((class color) (min-colors 16)) (:foreground "brightred" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 257)) (:inherit message-header-to :foreground "#d7801a")) (((class color) (min-colors 256)) (:inherit message-header-to :foreground "#d7801a")) (((class color) (min-colors 16)) (:inherit message-header-to :foreground "brightred"))))
 '(message-header-other ((((class color) (min-colors 257)) (:foreground "#9c91e4")) (((class color) (min-colors 256)) (:foreground "#9c91e4")) (((class color) (min-colors 16)) (:foreground "brightmagenta"))))
 '(message-header-newsgroups ((((class color) (min-colors 257)) (:foreground "#e2c770")) (((class color) (min-colors 256)) (:foreground "#e2c770")) (((class color) (min-colors 16)) (:foreground "yellow"))))
 '(message-header-xheader ((((class color) (min-colors 257)) (:foreground "#7f7f80")) (((class color) (min-colors 256)) (:foreground "#909090")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(message-separator ((((class color) (min-colors 257)) (:foreground "#555556")) (((class color) (min-colors 256)) (:foreground "#6b6b6b")) (((class color) (min-colors 16)) (:foreground "brightblack"))))
 '(message-mml ((((class color) (min-colors 257)) (:foreground "#555556" :slant italic)) (((class color) (min-colors 256)) (:foreground "#6b6b6b" :slant italic)) (((class color) (min-colors 16)) (:foreground "brightblack" :slant italic))))
 '(message-cited-text ((((class color) (min-colors 257)) (:foreground "#fb2874")) (((class color) (min-colors 256)) (:foreground "#fb2874")) (((class color) (min-colors 16)) (:foreground "magenta"))))
 '(widget-button-pressed ((((class color) (min-colors 257)) (:foreground "#e74c3c")) (((class color) (min-colors 256)) (:foreground "#e74c3c")) (((class color) (min-colors 16)) (:foreground "red"))))
 '(widget-documentation ((((class color) (min-colors 257)) (:foreground "#b6e63e")) (((class color) (min-colors 256)) (:foreground "#b6e63e")) (((class color) (min-colors 16)) (:foreground "green"))))
 '(window-divider ((t (:inherit vertical-border))))
 '(window-divider-first-pixel ((t (:inherit window-divider))))
 '(window-divider-last-pixel ((t (:inherit window-divider))))
